// todoapp/client/src/App.jsx
import React from "react";
import { Routes, Route, Link } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";

import AddTodo from "./components/AddTodo";
import Todo from "./components/Todo";
import TodosList from "./components/TodosList";

function App() {
  return (
    <div>
      <nav className="navbar navbar-expand navbar-dark bg-dark">
        <a href="/Todos" className="navbar-brand ms-3">
          TodoApp
        </a>        
        <div className="navbar-nav mr-auto">
          <li className="nav-item">
            <Link to={"/Todos"} className="nav-link">
              Todos
            </Link>
          </li>
          <li className="nav-item">
            <Link to={"/add"} className="nav-link">
              Add
            </Link>             
          </li>
        </div>
      </nav>

      <div className="container mt-3" >
        <Routes>
          <Route path="/" element={<TodosList/>} />
          <Route path="/Todos" element={<TodosList/>} />
          <Route path="/add" element={<AddTodo/>} />
          <Route path="/Todos/:id" element={<Todo/>} />
        </Routes>
      </div>
    </div>
  );
}

export default App;

// tutorialapp/vuetifyts-client/src/App.vue
<template>
  <div id="app">
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <router-link to="/" class="navbar-brand">tutos</router-link>
      <div class="navbar-nav mr-auto">
        <li class="nav-item">
          <router-link to="/tutorials" class="nav-link">Tutorials</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/add" class="nav-link">Add</router-link>
        </li>
      </div>
    </nav>

    <div class="container mt-3">
      <router-view />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
// import 'vuetify/dist/vuetify.min.css';
// import 'vuetify/styles';

export default defineComponent({
  name: "App",
});
</script>
